### ISSUE TITLE
doesnt run scripts

### ISSUE THREAD

**Issue by markrharvey** [SpacehuhnTech/WiFiDuck#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your problem

whenever i try to run a script it tells me that it is running but nothing happens 

### Steps to reproduce

go to  wifi.duck 
scroll down to script 
click run 
banner changes from connected to running 
nothing happens on computer that it is pluged into 

### What hardware are you using?

DIY Build (D1 mini and pro micro)

**Comment by Ciph3rCat** [comment]
Same issue here with cjmcu-3212, any help?

**Comment by Z3R0NULL** [comment]
> Same issue here with cjmcu-3212, any help?

Hii i flashed this on my CJMCU-3212 but theres say in Yellow "Internal Connection Problem" why? you have solution ?
