### ISSUE TITLE
Only first line runs

### ISSUE THREAD

**Issue by slash128v6** [SpacehuhnTech/WiFiDuck#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your problem

Only first line of script runs

### Steps to reproduce

1. Create script.
2. Click run.
3. Web interface shows Internal Connection Problem.
4. Serial monitor shows Interpreting: and the first line of the script.
5. If I make the first line of the script LED 255 255 255 and run the RGB LED changes to white, so it appears that line executes, but no further lines execute.

### What hardware are you using?

DYI Build (Pro Mini + D1 Mini)

**Comment by slash128v6** [comment]
I just tried flashing this same firmware to a DSTIKE board that I purchased. After flashing the Arduino code the DSTIKE now only executes the first line of any script and status shows "Internal connection problem". So now the DSTIKE that I purchased is non-functional.

**Comment by prawinrai1993** [comment]
try referring to #94 to resolve the issue. I had same issue before.
