### ISSUE TITLE
LOCALE RU

### ISSUE THREAD

**Issue by Egor2101** [SpacehuhnTech/WiFiDuck#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your Question

I can't switch keyboard layout... The example from the repository doesn't work...

**Comment by spacehuhn** [comment]
What example are you referring to?
And did you update/reflash the firmware?
Any other things you tried?

**Comment by Egor2101** [comment]
> Какой пример вы имеете в виду? А вы обновляли/перепрошивали прошивку? Любые другие вещи, которые вы пробовали?
The latest firmware. Everything works, except for changing the language. STRING displays the current system language regardless of LOCALE. 
example: test.script
