### ISSUE TITLE
Any problems with mac os keyboard profiler?

### ISSUE THREAD

**Issue by SSBhaumik** [SpacehuhnTech/WiFiDuck#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your Question

Does the DIY wifi duck run seamlessly on mac os given the settings prescribed in your video tutorial or we need to do something about apple identifier code ?

**Comment by spacehuhn** [comment]
In Arduino when flashing atmega_duck, you can select the Keyboard USB VID/PID from a list of predefined devices
<img width="576" alt="grafik" src="https://user-images.githubusercontent.com/3826044/151777137-8f453325-2a87-4063-a1d9-32b2b27a9135.png">

**Comment by SSBhaumik** [comment]
Thank you so much you're like an excellent mentor, i have great respect for you. Although I don't know a lot about coding but your tutorials are easy to understand.

**Comment by SSBhaumik** [comment]
Can i use this apple id on windows too?

**Comment by SSBhaumik** [comment]
Ok tested it works on windows, pro micro and d1 mini setup like yours. After flashing was showing internal connection error but i reset my d1 mini then it was running fine.
