### ISSUE TITLE
Problem with SS Micro

### ISSUE THREAD

**Issue by adamff1** [SpacehuhnTech/WiFiDuck#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your problem

The AP network won't show up (SS Micro)

### Steps to reproduce

1. I flashed my ESP8266 through my SS Micro
2. I wired everything up as following:
ESP8266 | Atmega32u4
`D1` alias `GPIO 5` → `3` alias `SCL`
`D2` alias `GPIO 4` → `2` alias `SDA`
 `GND` → `GND`
VCC | 3.3
3. I flashed atmega_duck

And the AP network is not showing up. Also, the ESP8266 LED won't blink. Do I have to change some vars on config.h or something?

### What hardware are you using?

SS Micro and ESP8266

**Comment by Soumy100** [comment]
![IMG_0227](https://user-images.githubusercontent.com/91321036/164942712-9ea183d0-bd7a-4e1f-8361-3ce240fe9c31.jpg)
![IMG_0231](https://user-images.githubusercontent.com/91321036/164942716-247eff3d-651b-4311-bf37-70cff8f2e637.jpg)
![IMG_0228](https://user-images.githubusercontent.com/91321036/164942717-20f7ffe7-4767-4914-b675-1c79379ca3e6.jpg)
**Same Issue is with me I have connected as per the instructions and then after I flashed my boards and then I connected power to micro but the wifiduck AP is not showing. I don't know where is the issue so I check pro micro and d1mini its working fine and changed jumper cables but same issue**  _I have shared the images of my connections please have a look_
