### ISSUE TITLE
work on pi pico w?

### ISSUE THREAD

**Issue by pythondemon** [SpacehuhnTech/WiFiDuck#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your Question

work on pi pico w?

**Comment by HugoMskn** [comment]
I'm not sure, as it need a custom firmware adapted for special chips, but I think you can do a badusb with a pico W 
https://www.youtube.com/watch?v=e_f9p-_JWZw&pp=ugMICgJmchABGAE%3D
