### ISSUE TITLE
bare esp12e connections?

### ISSUE THREAD

**Issue by PineMaster** [SpacehuhnTech/WiFiDuck#36]
hello im very new to esp boards, i have a 5v arduino pro micro and a bare esp12e, how can i connect them

**Comment by spacehuhn** [comment]
Hey sorry I didn't see this issue earlier. 
I updated connections section a few days ago: https://github.com/SpacehuhnTech/WiFiDuck#connections
You need a 5V to 3.3V regulator like the AMS1117 to power the ESP12.
