### ISSUE TITLE
Serial Support?

### ISSUE THREAD

**Issue by DX94-Quas** [SpacehuhnTech/WiFiDuck#41]
Hello, I bought a generic rubber ducky board a long time ago and noticed there was an updated version of the Wifi duck project(this repository), but i didnt read enough so I proceeded to flash it without noticing that the new code comunicates the ESP8266 with the 32u4 via i2c and not via serial like the older code.
Is there any chance of serial support for older boards?

**Comment by spacehuhn** [comment]
For the ESP8266 you must select `Protocol->Serial`
![grafik](https://user-images.githubusercontent.com/3826044/83650545-bf48b480-a5b8-11ea-8b1d-c6872d26db79.png)  

The default selection `Auto (I2C & Serial)` for the Atmega however should be fine as is.
![grafik](https://user-images.githubusercontent.com/3826044/83650700-ebfccc00-a5b8-11ea-885a-c2cabc2f39a6.png)

Keep in mind that using the hardware serial port will make it difficult to flash the ESP8266, as you'd need to disconnect the pins first.
