### ISSUE TITLE
Please tell me right connection of the electric circuit.

### ISSUE THREAD

**Issue by renzokushineshinemisairu** [SpacehuhnTech/WiFiDuck#42]
It was wrote  on readme that " Here's a map of the pins that need to be connected. " .
There are three connections(D1 to SCL, D2 to SDA, GND to GND).

========================
ESP8266 | Atmega32u4
-- | --
D1 alias GPIO 5 | 3 alias SCL
D2 alias GPIO 4 | 2 alias SDA
GND | GND |

=========================

but, the image below the table shows that there is another connection.(5v to RAW?)
https://github.com/SpacehuhnTech/WiFiDuck/blob/master/img/diy_example.jpg

I've already tried the former pattern(=the three connection), but the system didn't move.
Please tell me right connection of the electric circuit.

**Comment by spacehuhn** [comment]
Thanks for asking. This part was actually not explained. I now added a note to the README: 
https://github.com/SpacehuhnTech/WiFiDuck/blob/master/README.md#connections
