### ISSUE TITLE
Would be possible to run the script on a Attiny85? [Question] 

### ISSUE THREAD

**Issue by Cmd-Monkey** [SpacehuhnTech/WiFiDuck#43]
I know that the Attiny85 has little memory space, but he can emulates a keyboard as well as the Arduino Leonardo, so could be possible to run in it?
Thanks and sorry for the bad English.

**Comment by spacehuhn** [comment]
No. An Attiny85 does not have enough resources (flash, RAM, speed, IOs) to support the full functionality of this project.
