### ISSUE TITLE
help error running script!

### ISSUE THREAD

**Issue by shooter47** [SpacehuhnTech/WiFiDuck#46]
I am running wifiduck on a Debkit NodeMcu v3 and I have an error, the error is from the attached image.

the version i am using for wifi duck is 1.0.0

![Screenshot_2020-06-13-00-37-13](https://user-images.githubusercontent.com/43307838/84562154-7d81e180-ad0f-11ea-80ec-4825ccee0753.png)

**Comment by jLynx** [comment]
https://github.com/SpacehuhnTech/WiFiDuck/blob/master/README.md#hardware

**Comment by shooter47** [comment]
> https://github.com/SpacehuhnTech/WiFiDuck/blob/master/README.md#hardware

friend I already did it like this manual, I just want help!

**Comment by jLynx** [comment]
You didn't post any photos on how you wired it up

**Comment by spacehuhn** [comment]
The error tells you that the communication between both microcontrollers (ESP8266 and Atmega32u4) has issues.
Maybe check the wiring and all connections?

We need more information in order to help you out @shooter47 
What are the steps you made to create the device?
Did you follow the steps closely https://github.com/SpacehuhnTech/WiFiDuck/blob/master/README.md#hardware?

**Comment by shooter47** [comment]
> El error le dice que la comunicación entre ambos microcontroladores (ESP8266 y Atmega32u4) tiene problemas.
> ¿Quizás verifique el cableado y todas las conexiones?
> 
> Necesitamos más información para ayudarte @ shooter47
> ¿Cuáles son los pasos que hiciste para crear el dispositivo?
> ¿Seguiste los pasos de cerca https://github.com/SpacehuhnTech/WiFiDuck/blob/master/README.md#hardware ?

thank you very much friend, you are great @spacehuhn. I already found that the problem was in the wiring, I just have a question of how can I use it with an esp8266 01, regards.

**Comment by spacehuhn** [comment]
You can edit the pins used for i2c in [`espduck/config.h`](https://github.com/SpacehuhnTech/WiFiDuck/blob/master/esp_duck/config.h#L23) or you [enable serial](https://github.com/SpacehuhnTech/WiFiDuck/blob/master/esp_duck/config.h#L23) and use RX and TX pins.
