### ISSUE TITLE
locale ES: Impossible to write apostrophe (')

### ISSUE THREAD

**Issue by andreswhr** [SpacehuhnTech/WiFiDuck#51]
Testing the ES layout on my WiFiDuck:

```
REM es char test
LOCALE ES
GUI r
notepad.exe
ENTER
DELAY 200
STRING !"#$%&'()*+,-./0123456789: =>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_abcdefghijklmnopqrstuvwxyz{|}~¿¡ñÑçÇºª€·¨`
ENTER

```

returns the following in a notepad:

```

!"#$%&.()*+,-./0123456789: =>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_abcdefghijklmnopqrstuvwxyz{|}~¿¡ñÑçÇºª€·¨`

```

As you can see, every character is translated correctly except for the 7th one, where the apostrophe (') is translated into a dot (.)

This is making it impossible for me to type powershell commands into the wifiduck, as that character is commonly required.

In a common spanish keyboard layout, (') is located just after the top numeric line, so it is like this:
ESC 1 2 3 4 5 6 7 8 9 0 ' ¡ BACKSPACE

Any advice will be appreciated. Thanks in advance.

**Comment by Bommlon** [comment]
You can try to fix this by modifying the keyboard layout, [here's how](https://spacehuhn.wiki/wifiduck/development/translatekeyboardlayout/).

**Comment by Bommlon** [comment]
You can try to fix this by modifying the keyboard layout, [here's how](https://spacehuhn.wiki/wifiduck/development/translatekeyboardlayout/).

**Comment by spacehuhn** [comment]
Thank you for the report. Seems like our translator made a little mistake. Luckily I was able to find the bug (https://github.com/SpacehuhnTech/WiFiDuck/commit/ca3a1975c31f342da7db8e5bd554fc30dbb30f67).
