### ISSUE TITLE
can i use this in wifi cactus WHID

### ISSUE THREAD

**Issue by rohindh-hub** [SpacehuhnTech/WiFiDuck#54]
> Please search for existing (open and closed) issues to avoid duplicates.
I have a wifi cactus WHID which is running ESPloitV2. so, how do I install wifi duck in that

**Comment by Sekisback** [comment]
Yes you can. But you need the ESP-Programmer from whid-injector
Installation: 
Initial Flashing
Arduino -> Tool -> Board -> LilyPad Arduino USB
1. Install https://github.com/whid-injector/WHID/tree/master/tools/ESP_Programmer/ESP_Programmer.ino

For the Duck ,make sure you have the following library installed
https://github.com/spacehuhn/SimpleCLI
https://github.com/me-no-dev/ESPAsyncTCP
https://github.com/me-no-dev/ESPAsyncWebServer

2. ESP8266
Arduino -> Tool -> Board -> Generic ESP8266 Module
Flash Size - "4M (3M SPIFFS)"
Open https://github.com/SpacehuhnTech/WiFiDuck/tree/master/esp_duck/esp_duck.ino with the Arduino IDE
Press Upload
