### ISSUE TITLE
Internal Connection Problem

### ISSUE THREAD

**Issue by kopfjaeger1** [SpacehuhnTech/WiFiDuck#55]
I have an ATmega32u4 Arduino Pro Micro and ESP8266 12-E Modules (NodeMCU 1.0). ** I dont have any LED :)
I connected them on breadbord just like your Tutorial (with wire jumps)
I flashed the software, everything is fine but when I connect to the Esp interface to run the scripts it appears Internal Connection Problem

Can you guys give me any suggestion on what to do?
Thanks :)

**Comment by Bommlon** [comment]
There is a page about this problem in the [Wiki](https://spacehuhn.wiki/wifiduck/troubleshooting/).
