### ISSUE TITLE
Where is the info about vendors (USB ID)?

### ISSUE THREAD

**Issue by s-c-p** [SpacehuhnTech/WiFiDuck#56]
> Please search for existing (open and closed) issues to avoid duplicates.
Hi,

I remember setting the ATmega32u4 board to mimic some Logitech keyboard.

But searching the source code for the word `logitech` [doesn't return anything](https://github.com/SpacehuhnTech/WiFiDuck/search?q=logitech), so where is the struct and data containing information about vendor ID and stuff like that?

I am curious because in my fork, I'd like to implement more vendors and mice also.

Thanks.

**Comment by spacehuhn** [comment]
That's part of the Arduino Package, rather than the firmware itself. You can find the Vendor IDs in `boards.txt`. For the WiFiDuck AVR package have a look here: https://github.com/SpacehuhnTech/arduino-avr/blob/wifiduck/boards.txt
