### ISSUE TITLE
CJMCU-3212 PCB Support

### ISSUE THREAD

**Issue by nbwiss** [SpacehuhnTech/WiFiDuck#58]
Merry Christmas!

I just got a new chinese PCB called the CJMCU-32 12 that has the ESP module, AtMega and sdcard slot all in one pcb. I tried flashing it with your old version using a tutorial linked [here](https://github.com/puckk/CJMCU-3212) , and it worked well. I first flashed the AtMega with the ESP programmer, bridged the pads (as the tutorial says) and got your old wifi_ducky repo to work on it. I try the same steps but this time using an esp bin file from the new repo WIFI DUCK, and flashed the new AtMega firmware, and I just think its incompatible. Is there a way this board could work? Its a nice pcb, and I'd like to take advantage of the new features of the new repo. I have the [pinout](http://myosuploads3.banggood.com/products/20190102/20190102202550CJMCU-32U4TFWIFIforreference.pdf) linked, I think it doesnt work due to the way payloads are communicated between the esp and atmega modules.

**Comment by spacehuhn** [comment]
Is this maybe realted to this discussion? https://github.com/SpacehuhnTech/WiFiDuck/issues/30
