### ISSUE TITLE
What device do I connect to victim's pc??

### ISSUE THREAD

**Issue by Rocky471** [SpacehuhnTech/WiFiDuck#59]
I am very impressed by the DIY Wi-Fi Duck project, but I am not able to know whether to insert the ESP8266 board of the Arduino Pro Micro board to the victim's PC? 

Also, can you please tell on how to control the victim's pc after connecting either the ESP board or the other one.

How long should I keep it connected to the victim's pc and how to control it remotely?

It would be really helpful if you answered mu questin and cleared my doubts.

Best regards,
A Wifi Rubber Ducky

**Comment by spacehuhn** [comment]
You connect the Atmega32u4 to the computer. For your other questions, I recommend you study the [Readme](https://github.com/SpacehuhnTech/WiFiDuck)
