### ISSUE TITLE
new .bin official releases 

### ISSUE THREAD

**Issue by MrCook1es** [SpacehuhnTech/WiFiDuck#62]
Hi big boss,
since precompiled .bin v1.0.0 release, you've made several updates to the sources.
https://github.com/SpacehuhnTech/WiFiDuck/releases
i read that 43 changes have been made, would you like to re-run the sources and publish a .bin v1.0.1?
so we can upgrade easily directly from the web interface ♥

**Comment by RithyNicolasTAN** [comment]
Hi,
Thanks for your application.
Like @MrCook1es, I've bought a WiFiDuck on Aliexpress and I want to upgrade it with the lastest version including FR locale.
Can you publish a new bin in order to upgrade easily from the web interface ?
Thanks

**Comment by MrCook1es** [comment]
no response from developer?

**Comment by spacehuhn** [comment]
Hi, I'm prepping a new release. But just as a heads-up: you'll need to flash both the atmega (through Arduino IDE) to get the new keyboard layouts and the ESP8266 (through the web interface).
