### ISSUE TITLE
My Malduino W Displays: Internal Connection Error. Please Help Me This Is Driving Me Crazy.

### ISSUE THREAD

**Issue by S1m1B1lly** [SpacehuhnTech/WiFiDuck#65]
Does Someone Know What To Do When Malduino W Doesnt Stop Saying Internal Connection Error?
Pls  Help

**Comment by ghost** [comment]
fixed

**Comment by huntman312** [comment]
how did you fix this?

**Comment by huntman312** [comment]
> 
> 
> fixd

how did you fix this?

**Comment by S1m1B1lly** [comment]
Just email Support@maltronics.com with any issue.
for me they sent two files.
it didnt work becuase a mismatch between the  versions of the chips and the software.
Email them and they tell you how.

**Comment by jay-nutt3r** [comment]
@huntman312 don't suppose you have them files still?

**Comment by jay-nutt3r** [comment]
@S1m1B1lly Don't suppose you still have the files?

**Comment by jay-nutt3r** [comment]
@huntman312 did you also fix this issue?

**Comment by huntman312** [comment]
I believe i still do. But i wont be home for a while to check (like 6 hours). But if you email Support@maltronics.com he will get back to you with the files and instructions probably sometime really early in the morning if you live United States.

**Comment by lukariosmen** [comment]
@jay-nutt3r hi have you fixed this issue? I wrote an email to the support, but have not received any response.

**Comment by MonsieurBark** [comment]
same pb Internal Connection Error and the support don't respond :(

**Comment by boxxyhf** [comment]
> I believe i still do. But i wont be home for a while to check (like 6 hours). But if you email [Support@maltronics.com](mailto:Support@maltronics.com) he will get back to you with the files and instructions probably sometime really early in the morning if you live United States.

Could you perhaps still share the two files?

**Comment by lukariosmen** [comment]
[malw-06-07-2022 (1).zip](https://github.com/SpacehuhnTech/WiFiDuck/files/9610741/malw-06-07-2022.1.zip)
Hi. Here are the needed files :).

**Comment by boxxyhf** [comment]
> [malw-06-07-2022 (1).zip](https://github.com/SpacehuhnTech/WiFiDuck/files/9610741/malw-06-07-2022.1.zip) Hi. Here are the needed files :).

Thanks!  That fixed it. Working as a charm again!

**Comment by Fox8ter** [comment]
Hello @lukariosmen , (or @boxxyhf )

How to use these files?
can you provide the instructions ?

REgards

**Comment by boxxyhf** [comment]
Hello, @Fox8ter,

Follow this guide: http://docs.maltronics.com/malduino-w/troubleshooting/
But use the files in @lukariosmen's post.

**Comment by Fox8ter** [comment]
Same for the uf2 file?

**Comment by Fox8ter** [comment]
Yeah same... All works now... Really thx.

**Comment by Miliik** [comment]
how do you use the uf2 as the the exe just let you choose .bin files ?
btw , i got the error right after following the reset guide ^^

**Comment by BlackCube4** [comment]
I have the same problem :/

**Comment by Miliik** [comment]
Sorry for the late reply, but if this can help someone:
With the previous file, you’ll need to plug the device in, then double-tap the B button ,a mass-storage drive will appear.
Place the .uf2 file there, and the drive will disconnect automatically.

Then unplug and replug the MalDuino while holding the A button, and flash it following the procedure with the .bin file.

Wait a bit, then unplug/replug again, and the issue should be solved.
