### ISSUE TITLE
New WifiDuck compatibility with WHID Cactus?

### ISSUE THREAD

**Issue by IMExperts** [SpacehuhnTech/WiFiDuck#67]
Is the new WifiDuck firmware compatible with WHID Cactus? Is there any tutorial on how to flash it in WHID? All I can find is flashing the old Wifi_ducky tutorials on the web. I had to buy WHID just because of the unavailability of Wifi Duck in my region.

**Comment by IMExperts** [comment]
@spacehuhn please look into my question. thanks

**Comment by Bommlon** [comment]
This was answered in [issue #54](https://github.com/SpacehuhnTech/WiFiDuck/issues/54#issuecomment-731774999). Look into it and see if it helps.

**Comment by redxhawk** [comment]
> This was answered in [issue #54](https://github.com/SpacehuhnTech/WiFiDuck/issues/54#issuecomment-731774999). Look into it and see if it helps.

Tried it but it didn't work.
