### ISSUE TITLE
Random Input

### ISSUE THREAD

**Issue by shineyes** [SpacehuhnTech/WiFiDuck#72]
Hello,
I just received this today. I flashed the updated version. I tried to run a short script that checked the devices IP and it was having troubles. It would randomly open desktop shortcuts or only print 1/3rd of the string. 

This is the script I used:

WINDOWS r
STRING powershell
ENTER
STRING ipconfig
ENTER

Thanks so much,

N.H

**Comment by Z3R0NULL** [comment]
Hello, maybe this because you have to use "LOCALE <COUNTRY CODE> to the target PC...
like if you are from spain "LOCALE ES" to the top of your Ducky Script :D
