### ISSUE TITLE
how i can make this hardware using teensy 2 ?

### ISSUE THREAD

**Issue by generic0808** [SpacehuhnTech/WiFiDuck#73]
hello , i have teensy 2 which has the same microcontroller used in this project but i can't figure out how i can do the same project with it regarding the arduino code " atmega_duck.ino " it will not work on the teensy 2 .. also pin connections looks good except the raw pin which is not present in the teensy 2 but i used vcc instead !

**Comment by spacehuhn** [comment]
This project is made for ATmega32u4 and ESP8266. We don't plan on supporting the teensy 2 at this point.
