### ISSUE TITLE
[CA-FR] Keyboard Locale Programming

### ISSUE THREAD

**Issue by Build-0-Matic** [SpacehuhnTech/WiFiDuck#77]
Hi!
I'm trying to create a keyboard locale for the CA_FR keyboard and I'm really struggling.
While I did manage to convert most of the keyboard layout, I'm really struggling with the accented letters.
For the éÉ keys (which should be the easiest since they're available in the extended ASCII tables, I found the code, converted it to hex in the following fashion
`const uint8_t extended_ascii_ca_fr[] PROGMEM = {
    0x82, KEY_NONE, KEY_SLASH,            // é
    0x90, KEY_MOD_LSHIFT, KEY_SLASH,      // É
};`
but the letters just won't print on the screen when I send them to the duck.

Also, we have a bunch of letters (èêëôîçï) which are made using "sticky keys" where you first press the accent key and then the letter you want accented ^+e=ê
How in the world do I program those?

Thanks!

**Comment by Aprilox** [comment]
Hello, thank you for your feedback I actually noticed during my modification for French keyboard, I did not find a solution because the US keyboard does not have an accent, I will look into the question if you have anything new do not hesitate :)

**Comment by Aprilox** [comment]
I have something new! I tried to copy the whole `const uint8_t utf8_**gb**[] PROGMEM = {` and for my part in "é" I had "€" so I modified the keys for my language and it's good I have an "é"

**Comment by Aprilox** [comment]
Here is my solution to adapt for the CA keyboard
`https://www.utf8-chartable.de/unicode-utf8-table.pl?utf8=0x` WEBSITE FOR CODE `HEXA look LATIN CAPITAL LETTER`
My CODE

const uint8_t utf8_fr[] PROGMEM = {
    0xc3, 0xa8, 0x00, 0x00, KEY_NONE, KEY_7,     // è
    0xc3, 0xa9, 0x00, 0x00, KEY_NONE, KEY_2,     // é
    };

**Comment by Build-0-Matic** [comment]
I'll have to try this out.
I was looking at the German keyboard to try and figure out how the heck this all worked.
I must say it's not exactly clear...
I did manage to get the regular keys converted through trial and error... but I would have rather done it while actually understanding how it works.
I think the command position in the list is important, but I don't know what it relates to.
And then the extended ascii and utf8 controls... still a mystery.

Thanks for the hard work.

**Comment by Build-0-Matic** [comment]
OK, I think I figure it out.
The hex values are for the character you actually want to print and the key presses are the combo you need to do to get the character.
If that's how it works, it really should be updated in the instructions!

**Comment by Aprilox** [comment]
yes that's how you find your hex code for the character here: https://www.utf8-chartable.de/unicode-utf8-table.pl?utf8=0x
and you say if this character is spotted then make this combination

example:

` 0xc3, 0xa8, 0x00, 0x00, KEY_NONE, KEY_7,                // è`

 0xc3, 0xa8, 0x00, 0x00, = the character 'é'
KEY_NONE, KEY_7,  = the key clicked if this character is found

**Comment by Build-0-Matic** [comment]
Cool. 
Thanks!
I'll work a bit on it this afternoon ☺

**Comment by Build-0-Matic** [comment]
Worked on it a bit and for some reason it just won't work.
here's the code
`const uint8_t utf8_ca_fr[] PROGMEM = {
    0xc3, 0xa0, 0x00, 0x00, KEY_APOSTROPHE,   KEY_A,        // à
    0xc3, 0xa2, 0x00, 0x00, KEY_LEFTBRACE,    KEY_A,        // â
    0xc3, 0xa4, 0x00, 0x00, KEY_RIGHTBRACE,   KEY_A,        // ä

    0xc3, 0xa7, 0x00, 0x00, KEY_RIGHTBRACE,   KEY_C,        // ç
    
    0xc3, 0xa9, 0x00, 0x00, KEY_NONE,         KEY_SLASH,    // é
    0xc3, 0xa8, 0x00, 0x00, KEY_APOSTROPHE,   KEY_E,        // è
    0xc3, 0xaa, 0x00, 0x00, KEY_LEFTBRACE,    KEY_E,        // ê
    0xc3, 0xab, 0x00, 0x00, KEY_RIGHTBRACE,   KEY_E,        // ë

    0xc3, 0xaf, 0x00, 0x00, KEY_RIGHTBRACE,   KEY_I,        // ï
    0xc3, 0xae, 0x00, 0x00, KEY_LEFTBRACE,    KEY_I,        // î

    0xc3, 0xb4, 0x00, 0x00, KEY_LEFTBRACE,    KEY_O,        // ô
    0xc3, 0xb6, 0x00, 0x00, KEY_RIGHTBRACE,   KEY_O,        // ö
    
    0xc3, 0xbb, 0x00, 0x00, KEY_RIGHTBRACE,   KEY_U,        // ü
    
    0xc3, 0x89, 0x00, 0x00, KEY_MOD_LSHIFT,   KEY_SLASH,    // É
    0xc3, 0x88, 0x00, 0x00, KEY_APOSTROPHE,   KEY_E,        // È
    0xc3, 0x8a, 0x00, 0x00, KEY_LEFTBRACE,    KEY_E,        // Ê
    0xc3, 0x8b, 0x00, 0x00, KEY_RIGHTBRACE,   KEY_E,        // Ë
};`
so nothing out of the ordinary there.
But when I send it the following
`LOCALE CA_FR
WINDOWS r
STRING notepad
ENTER
DELAY 1000
STRING #1234567890-=qwertyuiopasdfghjkl;«zxcvbnm,.é
ENTER
STRING |!"/$%?&*()_+QWERTYUIOPASDFGHJKL:»ZXCVBNM'.É
ENTER
STRING \±@£¢¤¬¦²³¼½¾§¶[]~{}°¯­´
ENTER
STRING âäàçêëèîïôöûÙüÂÄÀÇÊËÈÎÏÔÖÛÙÜ
ENTER`
all I get is this
`|1234567890-=qwertyuiopasdfghjkl;zxcvbnm,.
>!"/$%?&*()_+QWERTYUIOPASDFGHJKL:ZXCVBNM'.
\@[]~^¨

`
I added this at the end (which is not needed by the US keyboard I started with)
`static hid_locale_t locale_ca_fr {
      (uint8_t*)ascii_ca_fr, 128,
      (uint8_t*)utf8_ca_fr, sizeof(utf8_ca_fr) / 6
};`

but it didn't do anything...

**Comment by Aprilox** [comment]
I do not really understand the problem otherwise on my github you have my files for the adaptation for French keyboard try to copy the base of my file and adapt it

**Comment by Build-0-Matic** [comment]
I'm going to have to do that as I really don't understand what's going on...
Besides, replacing the stock FR keyboard is something that should be done anyways.

I'll take a look and post my findings.

**Comment by dosslee** [comment]
TqSent from my Huawei Mobile-------- Original Message --------Subject: Re: [SpacehuhnTech/WiFiDuck] Keyboard Locale Programming (#77)From: Build-0-Matic To: SpacehuhnTech/WiFiDuck CC: Subscribed 
I'm going to have to do that as I really don't understand what's going on...
Besides, replacing the stock FR keyboard is something that should be done anyways.
I'll take a look and post my findings.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/SpacehuhnTech/WiFiDuck/issues/77#issuecomment-907827870",
"url": "https://github.com/SpacehuhnTech/WiFiDuck/issues/77#issuecomment-907827870",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Build-0-Matic** [comment]
I think I'm slowly starting to figure it out...
it looks like the key press combos can't be just anything.
In the USB_HID file I found the following
`
 * Modifier masks - used for the first byte in the HID report.
 * NOTE: The second byte in the report is reserved, 0x00
#define KEY_MOD_LCTRL  0x01
#define KEY_MOD_LSHIFT 0x02
#define KEY_MOD_LALT   0x04
#define KEY_MOD_LMETA  0x08
#define KEY_MOD_RCTRL  0x10
#define KEY_MOD_RSHIFT 0x20
#define KEY_MOD_RALT   0x40
#define KEY_MOD_RMETA  0x80
`
So the modifiers have to be those keys.
Since here in Canada we use A LOT of modifiers for our keyboard, which is essentially a US keyboard with a whole bunch of other characters jammed on it, the duck can't handle it all.

I wonder if this is a bug or not?
I'll have to see if I can't add more keys as modifiers...

**Comment by Aprilox** [comment]
ok good luck in your research

**Comment by Build-0-Matic** [comment]
Doesn't look like it...
But at least I managed to get all the very important characters working. The rest is just a minor annoyance. But I'll keep trying things out. Maybe I can figure out a workaround.

**Comment by spacehuhn** [comment]
Hi, just pushed the CA-FR Layout. 
This is my test script. 
```
LOCALE ca-fr
DELAY 5000
STRING -,;./=0123456789aàbcçdeèéfghijklmnopqrstuùvwxyz_:!?'"()@*\&#%+$AÀBCÇDEÈÉFGHIJKLMNOPQRSTUÙVWXYZ«»[]{}°<>¬|~¤€`^¨âÂäÄĉĈêÊëËĝĜĥĤîÎïÏìÌĵĴôÔöÖòÒŝŜûÛüÜŵŴŷŶÿŸ
```
https://github.com/SpacehuhnTech/WiFiDuck/blob/master/atmega_duck/locale_cafr.h

**Comment by Build-0-Matic** [comment]
Wow!
This is a lot of additional characters!
Thanks for pulling this the rest of the way. I'm sure it's going to be useful for people who also have the strange characters in their language as it's a good starting point for re-mapping.

I'll test this out as soon as I get a chance.

**Comment by Build-0-Matic** [comment]
OK, I just did a test run.
I sent the duck the following:
LOCALE CA_FR
WINDOWS r
DELAY 500
STRING notepad
ENTER
DELAY 1000
STRING #1234567890-=qwertyuiopasdfghjkl;zxcvbnm,.
ENTER
STRING |!"/$%?&*()_+QWERTYUIOPASDFGHJKL:ZXCVBNM'.
ENTER
STRING éÉçÇêÊëËèÈïÏîÎôÔöÖ
ENTER
STRING \@[]~{}<>éÉ±£¢¤¬¦²³¼½¾§¶°¯­´«»
ENTER

But to my surprise, the output gave me the following:
/1234567890-=qwertyuiopasdfghjkl;zxcvbnm,.
>!`é$%É&*()_+QWERTYUIOPASDFGHJKL:ZXCVBNM`.

<"^¸|^¨'.

Notice the missing accents line...
I'll have to compare with the file I had made to see what the big difference is.

**Comment by Build-0-Matic** [comment]
OK, I think I'm starting to figure this out... the keymap that was posted is I believe for the Canadian Multilingual keymap, which is different than what I'm working on...

**Comment by spacehuhn** [comment]
Hmm that's disappointing. I set Windows to french canadian and it gave me the canadian multilingual layout by default. I assumed this would be the correct one. 
Which one are you using, and is it different from the regular french layout?

**Comment by Build-0-Matic** [comment]
It's very different from the French (from France) layout.
We have what is essentially a QWERTY with some characters grafted on.
The hard part are characters that require double combo keys. like è is actually like pressing [ ' ] + [ e ].
But doing È involves [ ' ] + [ shift e ]. And pressing the combos at the same time doesn't seem to work. It's like if there was a millisecond delay between the key strokes that was required in order for it to work properly.
For some characters like @ ~ { } [ ] \ ± £ ¢ ¤ ¬ ¦ ² ³ ¼ ½ ¾ ¯ ­° it's pretty easy as you just need to use the [ AltCar ] key.
But as soon as you combine [ AltCar ] + [ shift ] + whatever character needs it, it becomes a big nightmare.

**Comment by spacehuhn** [comment]
Could it be this? *Canadian French (legacy)*
![grafik](https://user-images.githubusercontent.com/3826044/151984538-b612b81f-6970-4acc-9f3b-dd321e6c07d6.png)

**Comment by spacehuhn** [comment]
Thanks! I think I found the right layout now. My mistake was that I set windows to French (Canadian) instead of English (Canadian) and therefore had a different selection of keyboard layouts. 
I'll update the layout soon.

**Comment by spacehuhn** [comment]
Ok, it's updated now. Hopefully, it will be correct this time! My test script:
```
LOCALE CA-FR
DELAY 5000
STRING -,;.«#¸<=0123456789abcdeéfghijklmnopqrstuvwxyz_:!?'"»()*/&%¨+>|$ABCDEÉFGHIJKLMNOPQRSTUVWXYZ­[]{}§¶@\¯°±¬¦~¤¢£½¼²³¾`´^âÂàÀáÁêÊèÈîÎìÌíÍôÔòÒóÓûÛùÙúÚýÝ
```

**Comment by Build-0-Matic** [comment]
YES! That now works perfectly!
I didn't think that it could be doable without resorting to inserting characters by using the alt ascii codes from the character map.
Thanks!
