### ISSUE TITLE
Can i use it on single board like NodeMcu v3 (esp8266)?

### ISSUE THREAD

**Issue by filipton** [SpacehuhnTech/WiFiDuck#79]
> Please search for existing (open and closed) issues to avoid duplicates.

**Comment by bigpuppy9999** [comment]
Sorry but did you ever find a solution to this?

**Comment by filipton** [comment]
> Sorry but did you ever find a solution to this?

Boards like nodemcu have usb to uart converter so you cant use it as hid device.
