### ISSUE TITLE
atmega_duck:6:10: fatal error: config.h: No such file or directory  #include "config.h"

### ISSUE THREAD

**Issue by tabman0790** [SpacehuhnTech/WiFiDuck#82]
```
atmega_duck:6:10: fatal error: config.h: No such file or directory
 #include "config.h"
```

how do i fix this

**Comment by Devsider** [comment]
Check if all your files are in the right place and if you have opened the correct folder.
Maybe also re-download from GitHub and try again.

**Comment by spacehuhn** [comment]
Right, you have to download and extract the projects .zip file first.
