### ISSUE TITLE
[CH]: Swiss Keyboard Layout 

### ISSUE THREAD

**Issue by Litchyi** [SpacehuhnTech/WiFiDuck#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What layout are you translating?

CH

### Where do you need help?

Hi, could you add the Swiss keyboard layout based on the german one because it's the same. Thanks and i love your project (sorry bad english).

**Comment by spacehuhn** [comment]
Hi. What are the differences to the German layout?

**Comment by Litchyi** [comment]
> Hi. What are the differences to the German layout?
The only difference (if I'm not mistaken) is that the abbreviations (ctrl, alt etc ...) are not in English on the German keyboard. But it's just the writing on the keyboard and it doesn't influence the code.

**Comment by Litchyi** [comment]
i think you can just copy and rename the german folders

**Comment by Litchyi** [comment]
After verification, there are differences because switzerland has several languages ​​... Sorry for my mistake.

**Comment by spacehuhn** [comment]
Just added the CH-FR layout: https://github.com/SpacehuhnTech/WiFiDuck/blob/master/atmega_duck/locale_chfr.h
```
LOCALE ch-fr
DELAY 5000
STRING -,.'§<$0123456789aàbcdeèéfghijklmnopqrstuvwxyz_;:!?"()*/&%°+=>£AäBçCDEFGHIJKLMNOöPQRSTUüVWXYZ[]{}@\#¬|¦~¢€`´^âÂÄÀáÁêÊëËÈÉîÎïÏìÌíÍôÔÖòÒóÓûÛÜùÙúÚ
```
and CH-DE: https://github.com/SpacehuhnTech/WiFiDuck/blob/master/atmega_duck/locale_chde.h
```
LOCALE ch-de
DELAY 5000
STRING -,.'§<$0123456789aäbcdefghijklmnoöpqrstuüvwxyz_;:!?"()*/&%°+=>£AàBçCDEèéFGHIJKLMNOPQRSTUVWXYZ[]{}@\#¬|¦~¢€`´^¨âÂÄÀáÁêÊëËÈÉîÎïÏìÌíÍôÔÖòÒóÓûÛÜùÙúÚ

```
