### ISSUE TITLE
LIBRARY NOT FOUND 

### ISSUE THREAD

**Issue by gravity2103** [SpacehuhnTech/WiFiDuck#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your problem

when i compile the sketch both for atmega and nodemcu

### Steps to reproduce

compile sketch 
it give error of library not found

### What hardware are you using?

pro micro+ nodemcu

### Anything else?

There are some library that are not there like HID , SimleCLI, ect and its giving error while compiling the code

**Comment by spacehuhn** [comment]
Make to precisely follow the setup guide https://github.com/SpacehuhnTech/WiFiDuck#flash-software
