### ISSUE TITLE
Internal connection  problem

### ISSUE THREAD

**Issue by prawinrai1993** [SpacehuhnTech/WiFiDuck#99]
https://github.com/SpacehuhnTech/WiFiDuck/blob/40456264ddff330b6c2c4310cfebbb472a0e6458/esp_duck/esp_duck.ino#L19

please update the delay to 1000ms to resolve the internal connection issue

**Comment by Egor2101** [comment]
> https://github.com/SpacehuhnTech/WiFiDuck/blob/40456264ddff330b6c2c4310cfebbb472a0e6458/esp_duck/esp_duck.ino#L19
> 
> please update the delay to 1000ms to resolve the internal connection issue
Does not work...

**Comment by mattybeens** [comment]
Didnt work for me either :(

**Comment by prawinrai1993** [comment]
> Didnt work for me either :(

try increasing delay. I am using nodemcu, for me worked. for other user 10000ms worked, who is using a d1 mini. not facing internal connection issue any more. Also scripts working super smooth.

**Comment by mattybeens** [comment]
i tried both of those times. I also have a dstike wifi duck V2 that has the same issue after updating.

**Comment by justusiv** [comment]
Tried both the 1000 and 10000 and i am having the same issue.

**Comment by slash128v6** [comment]
Same issue for me.

**Comment by spacehuhn** [comment]
I did some testing, and with debug enabled, I could reproduce the issue sometimes. Try disabling Debug if it isn't already. 
![grafik](https://user-images.githubusercontent.com/3826044/150880537-df35d280-2e88-4a07-a2ea-c6589e8580c9.png)

**Comment by slash128v6** [comment]
I have tried with Debug enabled and disabled. I tried on my DSTIKE board and now that board is no longer working. It appears to be an issue with I2C. I can run scripts via Serial between ESP and 32U4, albeit very slow.

**Comment by spacehuhn** [comment]
Using I2C (or serial given the right hardware) instead of the Auto mode also seems to make a difference sometimes. I have a growing suspicion that the atmega32u4 is partly responsible, as it seems to be very sensitive.
![grafik](https://user-images.githubusercontent.com/3826044/150884915-96b4ee5f-9d84-4dbe-bf41-04fb17b44b12.png)

**Comment by justusiv** [comment]
ok so that got me working... set both debugs to disable and both protocols to I2C.
Gonna play around but thanks for the info!

**Comment by slash128v6** [comment]
That seems to be working for me now too, thank you!

________________________________

**Comment by spacehuhn** [comment]
Hopefully, that's it 🤞 . I updated the Wifi Duck AVR boards so that these options are set by default from now on.

**Comment by slash128v6** [comment]
So far so good, I've reflashed a few times just to confirm and it's still working on both my DSTIKE board and DIY setup. Appreciate the help!

________________________________

**Comment by slash128v6** [comment]
I just tried on an ESP8266 connected to genuine Arduino Leonardo and it did not work, unfortunately. But the other setups are still working. Just wanted to let you know.
________________________________

**Comment by mattybeens** [comment]
https://www.amazon.com/dp/B08BJTS2N8?ref=ppx_yo2_dt_b_product_details&th=1
https://www.amazon.com/dp/B07S5HL54T?psc=1&ref=ppx_yo2_dt_b_product_details

Mines not working either :(

**Comment by slash128v6** [comment]
> https://www.amazon.com/dp/B08BJTS2N8?ref=ppx_yo2_dt_b_product_details&th=1 https://www.amazon.com/dp/B07S5HL54T?psc=1&ref=ppx_yo2_dt_b_product_details
> 
> Mines not working either :(

try disabling debug on both sketches and hard set protocol to I2C on both sketches. That got me working with the same hardware from Amazon.

**Comment by mattybeens** [comment]
> > https://www.amazon.com/dp/B08BJTS2N8?ref=ppx_yo2_dt_b_product_details&th=1 https://www.amazon.com/dp/B07S5HL54T?psc=1&ref=ppx_yo2_dt_b_product_details
> > Mines not working either :(
> 
> try disabling debug on both sketches and hard set protocol to I2C on both sketches. That got me working with the same hardware from Amazon.

I got it, i was dumb and had to use the "generic esp8266"  board

**Comment by prawinrai1993** [comment]
The solution works fine with disabling debug and selecting i2c. Also my board required generic esp8266 selection in ide before flash. works for both d1 wemos mini and esp8266.
